from .base import *

DEBUG = False
ALLOWED_HOSTS = (os.environ["DJANGO_HOST"],)

CORS_ALLOWED_ORIGINS = (os.environ["FRONTEND_ADDRESS"],)
CSRF_TRUSTED_ORIGINS = (os.environ["FRONTEND_ADDRESS"],)


# I NEED TO SET STATIC/MEDIA URLS AND ROOTS according to nginx configuration
# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR.parent / "staticfiles"
MEDIA_ROOT = BASE_DIR.parent / "media"
MEDIA_URL = "/media/"

# Use secure cookies in production (temporary - generated by AI needs review)
CORS_ALLOW_CREDENTIALS = True

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None"

SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "None"

SECURE_HSTS_SECONDS = 3600
SECURE_SSL_REDIRECT = True

### I need to get to know logging better, simple streamhandler for now
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "request_rotating": {
            "level": "INFO",
            "class": "core.logging.handlers.RequestCountRotatingHandler",
            "filename": str(LOGS_DIR / "request_response.log"),
            "max_requests": 6,
            "backupCount": 5,
            "formatter": "simple",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "request_response": {
            "handlers": ["request_rotating"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}
